# Generated by Django 4.1.13 on 2024-10-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_staff_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
