# Generated by Django 4.1.13 on 2024-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_phone_number_staff_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
